### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by RealOrangeOne** [clbarnes/coordinates#5]
The version currently available on PyPI doesn't ignore its `tests/` directory, and so installs it in virtual environments, causing unfortunate naming conflicts.

Could you release a version based on `master` to fix this, so the specific fix is available: https://github.com/clbarnes/coordinates/commit/0ee8f8168a155c4e25929dede54561750dfc2c64

**Comment by clbarnes** [comment]
Done, thanks for using!

**Comment by RealOrangeOne** [comment]
Not installed it yet, but the version on PyPI has been updated, and doesn't contain a `tests/` repo, so i'm pretty happy this is solved :tada: 

Thanks for such a quick turn-around!
