### ISSUE TITLE
Tag for 0.3.0 release

### ISSUE THREAD

**Issue by mildlyincompetent** [clbarnes/coordinates#7]
Would it be possible to add a tag on github for the 0.3.0 release - this exists on pypi but not on github?

**Comment by clbarnes** [comment]
Should be able to do this. Would a patch release at 0.3.1 with an associated tag be good enough for your purposes? There have been some minor updates to the build cruft (3.8 support on Travis, bumping versions of requirements) and it would be nice to keep everything in sync.

**Comment by mildlyincompetent** [comment]
Sure; all I'm really looking for is for the latest release on PyPi to have an associated Github tag (I'm packaging for NixOS and would like my package to be the same version as on PyPi but to also run tests, which of course aren't included in the PyPi release, so I'm building from Github).

**Comment by clbarnes** [comment]
I made a couple of changes to the build cruft, including locking the dependency versions in requirements.txt. Twine's latest version no longer supports python 3.5, so I've dropped that too; therefore I bumped the version to 0.4.0, which is now tagged in this repo, and uploaded to PyPI. Let me know if it all looks OK from your end!

**Comment by mildlyincompetent** [comment]
All looks good to me, thanks!
